name: pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: Create Virtual Environment
      run: python -m venv venv

    - name: Activate Virtual Environment
      run: source venv/bin/activate

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    # ref of az login action: <https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#use-the-azure-login-action-with-a-service-principal-secret>
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{secrets.AZURE_CREDENTIALS_OF_MY_SUBSCRIPTION}}'

    - name: Run Tests
      run: |
        pytest